{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidentgpt-sanitizer.fullname" . }}-secrets
  labels:
    {{- include "incidentgpt-sanitizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.hashKeySecretKey }}: {{ .Values.secretValues.hashKey | default "" | quote }}
  {{ .Values.secrets.authSharedSecretKey }}: {{ .Values.secretValues.authSharedSecret | default "" | quote }}
{{- end }}
