apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incidentgpt-enricher.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "incidentgpt-enricher.fullname" . }}
    app.kubernetes.io/component: "enricher"
data:
  metrics.yaml: |
    {{- toYaml .Values.metrics | nindent 4 }}