{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidentgpt-enricher.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "incidentgpt-enricher.fullname" . }}
    app.kubernetes.io/component: "enricher"
type: Opaque
stringData:
  {{ .Values.secrets.sanitizerAuthSharedSecretKey }}: {{ .Values.secretValues.sanitizerAuthSharedSecret | default "" | quote }}
{{- end }}
