apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-worker.fullname" . }}
  labels:
    {{- include "ai-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "ai-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
